<?php

namespace Database\Seeders;

use App\Models\DeliveryFee;
use Illuminate\Database\Seeder;

class DeliveryFeeSeeder extends Seeder
{
    public function run(): void
    {
        $zones = [
            ['name' => 'Agustinos', 'price' => 7000],
            ['name' => 'Alamos', 'price' => 6000],
            ['name' => 'Alcazares', 'price' => 8000],
            ['name' => 'Alferez real', 'price' => 8000],
            ['name' => 'Alhambra', 'price' => 9000],
            ['name' => 'Alta suiza', 'price' => 5000],
            ['name' => 'Altos de capri', 'price' => 6000],
            ['name' => 'Altos de granada', 'price' => 5500],
            ['name' => 'Amarelo', 'price' => 6000],
            ['name' => 'Americas', 'price' => 7000],
            ['name' => 'Arboleda', 'price' => 5000],
            ['name' => 'Argentina', 'price' => 5000],
            ['name' => 'Arrayanes', 'price' => 6500],
            ['name' => 'Asuncion', 'price' => 5500],
            ['name' => 'Autonoma', 'price' => 5500],
            ['name' => 'Baja suiza', 'price' => 5000],
            ['name' => 'Belen', 'price' => 5000],
            ['name' => 'Bengala', 'price' => 6500],
            ['name' => 'Betania', 'price' => 5500],
            ['name' => 'Bosque', 'price' => 8000],
            ['name' => 'Bosques del norte', 'price' => 7000],
            ['name' => 'Cable plaza', 'price' => 5000],
            ['name' => 'Cambulos', 'price' => 9000],
            ['name' => 'Camelia', 'price' => 5000],
            ['name' => 'Campin', 'price' => 5500],
            ['name' => 'Campoamor', 'price' => 6000],
            ['name' => 'Campohermoso', 'price' => 7000],
            ['name' => 'Caribe', 'price' => 6000],
            ['name' => 'Carola', 'price' => 5000],
            ['name' => 'Castellana', 'price' => 8000],
            ['name' => 'Cedros', 'price' => 5500],
            ['name' => 'Centenario', 'price' => 8000],
            ['name' => 'Centro', 'price' => 6000],
            ['name' => 'Cerro de oro', 'price' => 5000],
            ['name' => 'Cervantes', 'price' => 6000],
            ['name' => 'Chipre', 'price' => 7000],
            ['name' => 'Colinas', 'price' => 7000],
            ['name' => 'Colombia', 'price' => 5500],
            ['name' => 'Colon', 'price' => 7000],
            ['name' => 'Colseguros', 'price' => 5000],
            ['name' => 'Conjunto torrear', 'price' => 5000],
            ['name' => 'Cumbre', 'price' => 6000],
            ['name' => 'El palmar', 'price' => 6500],
            ['name' => 'Enea', 'price' => 7000],
            ['name' => 'Estambul', 'price' => 10000],
            ['name' => 'Estrella', 'price' => 5000],
            ['name' => 'Eucaliptos', 'price' => 7000],
            ['name' => 'Expoferias', 'price' => 8000],
            ['name' => 'Fanny gonzales', 'price' => 6000],
            ['name' => 'Fatima', 'price' => 5500],
            ['name' => 'Florida', 'price' => 10000],
            ['name' => 'Fundadores', 'price' => 6000],
            ['name' => 'Guamal', 'price' => 7000],
            ['name' => 'Isabella', 'price' => 7000],
            ['name' => 'La francia', 'price' => 8000],
            ['name' => 'La fuente', 'price' => 8000],
            ['name' => 'Laureles', 'price' => 5000],
            ['name' => 'Leonora', 'price' => 5000],
            ['name' => 'Liborio', 'price' => 7000],
            ['name' => 'Lleras', 'price' => 5500],
            ['name' => 'Lusitania', 'price' => 8000],
            ['name' => 'Malhabar', 'price' => 7000],
            ['name' => 'Malhabar bajo', 'price' => 7000],
            ['name' => 'Mall plaza', 'price' => 6000],
            ['name' => 'Malteria', 'price' => 10000],
            ['name' => 'Milan', 'price' => 5000],
            ['name' => 'Minitas', 'price' => 6000],
            ['name' => 'Niza', 'price' => 5000],
            ['name' => 'Nogales', 'price' => 8500],
            ['name' => 'Ondas de otun', 'price' => 6500],
            ['name' => 'Palermo', 'price' => 5000],
            ['name' => 'Palogrande', 'price' => 5000],
            ['name' => 'Palonegro', 'price' => 6500],
            ['name' => 'Panorama', 'price' => 9000],
            ['name' => 'Parque caldas', 'price' => 6000],
            ['name' => 'Parque del agua', 'price' => 7000],
            ['name' => 'Peralonso', 'price' => 6000],
            ['name' => 'Prado alto y medio', 'price' => 6500],
            ['name' => 'Prado bajo', 'price' => 6500],
            ['name' => 'Rambla', 'price' => 5000],
            ['name' => 'Rambla / residencias', 'price' => 5000],
            ['name' => 'Rosales', 'price' => 5000],
            ['name' => 'Saenz', 'price' => 5500],
            ['name' => 'San antonio', 'price' => 6000],
            ['name' => 'Sancancio', 'price' => 5500],
            ['name' => 'San cayetano', 'price' => 6000],
            ['name' => 'San joaquin', 'price' => 6000],
            ['name' => 'San jorge', 'price' => 5500],
            ['name' => 'San marcel', 'price' => 6000],
            ['name' => 'San marcel montanita', 'price' => 8000],
            ['name' => 'Santa helena', 'price' => 6000],
            ['name' => 'Santos', 'price' => 7000],
            ['name' => 'Sol', 'price' => 5500],
            ['name' => 'Sultana', 'price' => 5000],
            ['name' => 'Terrazas del rio', 'price' => 5500],
            ['name' => 'Torres san vicente', 'price' => 7000],
            ['name' => 'Toscana', 'price' => 5000],
            ['name' => 'Trebol / tejares', 'price' => 5500],
            ['name' => 'Uribe av paralela', 'price' => 5500],
            ['name' => 'Velez', 'price' => 5500],
            ['name' => 'Versalles', 'price' => 5000],
            ['name' => 'Villa carmenza', 'price' => 7000],
            ['name' => 'Villa del rio', 'price' => 6000],
            ['name' => 'Villa hermosa', 'price' => 6000],
            ['name' => 'Villa julia', 'price' => 8000],
            ['name' => 'Villa luz', 'price' => 6000],
            ['name' => 'Villa pilar', 'price' => 7500],
            ['name' => 'Viveros', 'price' => 6000],
        ];

        foreach ($zones as $zone) {
            DeliveryFee::updateOrCreate(
                ['name' => $zone['name']],
                [
                    'price' => $zone['price'],
                    'description' => null,
                    'is_active' => true,
                ]
            );
        }
    }
}
